/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_DelSig_1.h"
#include "VDAC8_1.h"
#include "UART_1.h"
#include "isr_1.h"
#include "Waveform_Reg.h"
#include "WaveDAC8_1.h"
#include "PWM_Out_1_aliases.h"
#include "PWM_Out_1.h"
#include "Debug_LED_ctrl.h"
#include "AMux_1.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "UART_1_IntClock.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

