/******************************************************************************
* Project Name		: Lab 3
* File Name			: main.c
* Version 			: **
* Device Used		: CY8C5888LTI-LP097
* Software Used		: PSoC Creator 3.1 SP2
* Compiler    		: ARM GCC 4.8.4, ARM RVDS Generic, ARM MDK Generic
* Related Hardware	: CY8CKIT059 PSoC 5 LP Prototyping Kit 
* Owner				: KLMZ
*
********************************************************************************
* Copyright (2015), Cypress Semiconductor Corporation. All Rights Reserved.
********************************************************************************
* This software is owned by Cypress Semiconductor Corporation (Cypress)
* and is protected by and subject to worldwide patent protection (United
* States and foreign), United States copyright laws and international treaty
* provisions. Cypress hereby grants to licensee a personal, non-exclusive,
* non-transferable license to copy, use, modify, create derivative works of,
* and compile the Cypress Source Code and derivative works for the sole
* purpose of creating custom software in support of licensee product to be
* used only in conjunction with a Cypress integrated circuit as specified in
* the applicable agreement. Any reproduction, modification, translation,
* compilation, or representation of this software except as specified above 
* is prohibited without the express written permission of Cypress.
*
* Disclaimer: CYPRESS MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, WITH 
* REGARD TO THIS MATERIAL, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* Cypress reserves the right to make changes without further notice to the 
* materials described herein. Cypress does not assume any liability arising out 
* of the application or use of any product or circuit described herein. Cypress 
* does not authorize its products for use as critical components in life-support 
* systems where a malfunction or failure may reasonably be expected to result in 
* significant injury to the user. The inclusion of Cypress' product in a life-
* support systems application implies that the manufacturer assumes all risk of 
* such use and in doing so indemnifies Cypress against all charges. 
*
* Use of this Software may be limited by and subject to the applicable Cypress
* software license agreement. 


3GL, John Dempsey, Kwesi, Haitham
*******************************************************************************/

#include <device.h>
#include "stdio.h"
#include <stdbool.h>




/*******************************************************************************
* Function Name: main
********************************************************************************
*
* Summary:
*  main() performs following functions:
*  1: Starts the ADC, UART, and 2 different DAC components.
*  2: Receives UART Input to sample ADC and return sample to UART
*     On 'C' or 'c' received: continuously transmits samples as they are completed.
*     On 'R' or 'r' received: single Read command, polls ADC and prints reading.
*     On 'X' or 'x' received: stops continuously transmitting samples.
*     On 'S' or 's' received: Switches between waveform DAC and constant voltage DAC
      On 'W' or 'w' received: toggle waveform generated by waveform DAC
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/


#define TRANSMIT_BUFFER_SIZE  16


uint8 recvChar = 0;     //stores received char from UART on interrupt
uint32 adcOut = 0;      //stores ADC result
bool continuousSending = false;     //polls ADC and sends Serial data continuously
uint8 dacState = 0;     //0 or 1 to choose between waveform DAC or constant voltage DAC
uint8 waveForm = 0;     //changes the waveform generated by waveform DAC

bool inputting_degrees = false;     //flag for if we're listening to numbers for serial connection

char TransmitBuffer[TRANSMIT_BUFFER_SIZE] = {0};  //transmit buffer for sending strings

int degree = 0;
int digit_place = 0;
int counter = 0;

long int DMA_ARRAY[1024];



//DMA

    /* Defines for DMA_1 */
#define DMA_1_BYTES_PER_BURST 1
#define DMA_1_REQUEST_PER_BURST 1
#define DMA_1_SRC_BASE (CYDEV_PERIPH_BASE)
#define DMA_1_DST_BASE (CYDEV_SRAM_BASE)

/* Variable declarations for DMA_1 */
/* Move these variable declarations to the top of the function */
uint8 DMA_1_Chan;
uint8 DMA_1_TD[1];


//function declarations
int Turn_servo_degrees(int degrees);

int exponentiate (int base, int exponent) {

    if (exponent == 0) return 1;
    int final = 1;

    int k = 1;
    for (k=1; k<=exponent; k++) {
	    final = final*base;
    }
    
    return final;
}
int Sing (int);


CY_ISR(DMA_Handler) {
    dma_interrupt_ClearPending();
    
    int i = 0;
    /*
    for (i = 0; i < 256; i++) {
        Sing(DMA_ARRAY[i]/1000);
    }
    */
    
}

//ISR triggered upon UART receiving data
CY_ISR(ReadSerial) {
    //interpret the data
    //S or s = switch between waveform and constant Voltage
    //R or r = read voltage
    //C or c = constant output data
    //X or x = stop constantly outputting data
    //W or w = switch waveform
    
    isr_1_ClearPending();   //apparently do this at beginning of ISR
    
    recvChar = UART_1_GetChar();
    sprintf(TransmitBuffer, "got this character: %d\r\n", recvChar);
    UART_1_PutString(TransmitBuffer);
    
    bool invalid = false;
    
    
    switch(recvChar)
    {
        case 0:
            //no new data
            break;
        case 'S':
        case 's':
            //switch flag for inputting degrees, next characters are numbers for servo degrees
            inputting_degrees = true;
            degree = 0;
            digit_place = 0;
            counter = 0;
            
            sprintf(TransmitBuffer, "Receiving degrees, digitplace: %d\r\n", digit_place);
            UART_1_PutString(TransmitBuffer);
            break;
        case 'R':
        case 'r':
            //Reads data and sends it to UART
            if(ADC_DelSig_1_IsEndConversion(ADC_DelSig_1_RETURN_STATUS)) {
                //adcOut = ADC_DelSig_1_CountsTo_mVolts(ADC_DelSig_1_GetResult16());
                adcOut = ADC_DelSig_1_CountsTo_mVolts(ADC_DelSig_1_GetResult8());
                sprintf(TransmitBuffer, "Single ADC Read: %lu\r\n", adcOut);
                UART_1_PutString(TransmitBuffer);
            }
            break;
        case 'C':
        case 'c':
            //Continuously sends data
            continuousSending = true;
            break;
        case 'X':
        case 'x':
            //Cancels continuously sending data
            continuousSending = false;
            break;
        case 'l':
        case 'L':
            Sing(300);
            break;
        case 'W':
        case 'w':
            Sing(600);
            break;
        case 'h':
        case 'H':
            Sing(55000);
            break;
        default:
            // Place error handling code here
            //lol no
            invalid = true;
            
            
            //ok maybe we'll print something
            UART_1_PutString("Invalid command!\r\n");
            break;    
    }
    
    if (invalid && inputting_degrees) {
        //assume its a number
        int num = recvChar - 48;
        
        Turn_servo_degrees(num * 15);
        /*
        sprintf(TransmitBuffer, "got this as num: %d\r\n", num);
        UART_1_PutString(TransmitBuffer);
        sprintf(TransmitBuffer, "got this as counter: %d\r\n", counter);
        UART_1_PutString(TransmitBuffer);
        sprintf(TransmitBuffer, "got this as degree: %d\r\n", degree);
        UART_1_PutString(TransmitBuffer);
        */
        
        inputting_degrees = false;
    }

        
        /*
        //otherwise w're listening for the numbers.  'X' means stop
    } else if (recvChar == 'x' || recvChar == 'X' ) {
        inputting_degrees = false;
        digit_place = 0;
        Turn_servo_degrees(degree);
    } else {
        //lastly we're accepting the input for the servo degrees
        //expecting numbers here
        degree = recvChar * 10;
        
        digit_place++;
        
        sprintf(TransmitBuffer, "recieved this char: %d, digit place: %d\r\n", recvChar, digit_place);
        UART_1_PutString(TransmitBuffer);
        sprintf(TransmitBuffer, "Processing degree input, this is our degree: %d\r\n", degree);
        UART_1_PutString(TransmitBuffer);

    
        
        */
        
}



int main()
{
    
    
    


/* DMA Configuration for DMA_1 */
    DMA_1_Chan = DMA_1_DmaInitialize(DMA_1_BYTES_PER_BURST, DMA_1_REQUEST_PER_BURST, 
    HI16(DMA_1_SRC_BASE), HI16(DMA_1_DST_BASE));
    DMA_1_TD[0] = CyDmaTdAllocate();
    CyDmaTdSetConfiguration(DMA_1_TD[0], 1024, DMA_1_TD[0], DMA_1__TD_TERMOUT_EN | TD_INC_DST_ADR);
    CyDmaTdSetAddress(DMA_1_TD[0], LO16((uint32)ADC_DelSig_1_DEC_SAMP_PTR), LO16((uint32)DMA_ARRAY));
    CyDmaChSetInitialTd(DMA_1_Chan, DMA_1_TD[0]);
    CyDmaChEnable(DMA_1_Chan, 1);






    isr_1_StartEx(ReadSerial);      //attach the interrupt
    dma_interrupt_StartEx(DMA_Handler); //attach DMA interrupt
    CYGlobalIntEnable;              //this one line wasted like an hour
    
    //start the stupid hardware thingies
    Speaker_PWM_Start();
    Servo_PWM_Start();
    ADC_DelSig_1_Start();
    UART_1_Start();                             //does anyone even read these?
    UART_1_SetRxInterruptMode(UART_1_RX_STS_FIFO_NOTEMPTY);     //enable interrupts via software

    WaveDAC8_1_Start();
    
    //initialize variables
    
    
    //Start ADC Conversion(s)
    ADC_DelSig_1_StartConvert();
    Waveform_Reg_Write(waveForm);         //initialize wavesignal for waveform DAC

    
    // Send message to verify COM port is connected properly 
    UART_1_PutString("COM Port Open\r\n");
    
    adcOut = ADC_DelSig_1_CountsTo_mVolts(ADC_DelSig_1_GetResult8());
    sprintf(TransmitBuffer, "Initialized read: %lu mV\r\n", adcOut);
    UART_1_PutString(TransmitBuffer);
    
    //for loop polls ADC continuously if the proper mode is selected
    for(;;)
    {     
        //check for proper mode
        if(false) {
            if(ADC_DelSig_1_IsEndConversion(ADC_DelSig_1_RETURN_STATUS))    //poll ADC
            {

                //adcOut = ADC_DelSig_1_CountsTo_mVolts(ADC_DelSig_1_GetResult16());  //save output
                adcOut = ADC_DelSig_1_CountsTo_mVolts(ADC_DelSig_1_GetResult8());
                //print data to UART
                sprintf(TransmitBuffer, "Continuous ADC Read: %lu mV\r\n", adcOut);
                UART_1_PutString(TransmitBuffer);
                
            }
        }
    }
    return 0;
}


int Turn_servo_degrees(int degree) {
    
    
    
    int amt = degree * 255 / 360;
    Servo_PWM_WriteCompare(amt);
    
    sprintf(TransmitBuffer, "writing these degrees to servo: %d\r\n", amt);
    UART_1_PutString(TransmitBuffer);
    
    return 0;    
}

int Sing(int thing) {
    sprintf(TransmitBuffer, "singing with value: %d\r\n", thing);
    UART_1_PutString(TransmitBuffer);
    
    Speaker_PWM_WriteCompare(thing);   
    //Speaker_PWM_WritePeriod(thing);
    
    return 0;
}





/* [] END OF FILE */
